- name: Set up local workstation
  hosts: local
  roles:
    - role: geerlingguy.java
      java_packages:
        - java-1.8.0-openjdk
    - role: iancleary.jetbrains_mono

- import_playbook: zsh.yml
- import_playbook: alacritty.yml
- import_playbook: tmux.yml
- import_playbook: code.yml
- import_playbook: util.yml
- import_playbook: browser.yml
- import_playbook: media.yml
- import_playbook: redshift.yml
