- name: Set up local workstation
  hosts: local

- import_playbook: zsh.yml
- import_playbook: alacritty.yml
- import_playbook: code.yml
- import_playbook: util.yml
- import_playbook: browser.yml
- import_playbook: media.yml
- import_playbook: redshift.yml
