#!/bin/bash
# code --list-extensions | xargs -L 1 echo code --install-extension --force
code --install-extension aaron-bond.better-comments --force
code --install-extension alexcvzz.vscode-sqlite --force
code --install-extension alygin.vscode-tlaplus --force
code --install-extension bbenoist.Nix --force
code --install-extension BeardedBear.beardedtheme --force
code --install-extension betterthantomorrow.calva --force
code --install-extension borkdude.clj-kondo --force
code --install-extension codezombiech.gitignore --force
code --install-extension eamodio.gitlens --force
code --install-extension EditorConfig.EditorConfig --force
code --install-extension esbenp.prettier-vscode --force
code --install-extension formulahendry.code-runner --force
code --install-extension GitHub.vscode-pull-request-github --force
code --install-extension hollowtree.vue-snippets --force
code --install-extension ms-azuretools.vscode-docker --force
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools --force
code --install-extension ms-python.python --force
code --install-extension octref.vetur --force
code --install-extension rebornix.ruby --force
code --install-extension redhat.java --force
code --install-extension redhat.vscode-yaml --force
code --install-extension rust-lang.rust --force
code --install-extension scala-lang.scala --force
code --install-extension scalameta.metals --force
code --install-extension sdras.vue-vscode-snippets --force
code --install-extension serayuzgur.crates --force
code --install-extension vadimcn.vscode-lldb --force
code --install-extension VisualStudioExptTeam.vscodeintellicode --force
code --install-extension vscjava.vscode-java-debug --force
code --install-extension vscjava.vscode-java-dependency --force
code --install-extension vscjava.vscode-java-pack --force
code --install-extension vscjava.vscode-java-test --force
code --install-extension vscjava.vscode-maven --force
code --install-extension vscode-icons-team.vscode-icons --force
code --install-extension vscoss.vscode-ansible --force
code --install-extension wingrunr21.vscode-ruby --force
code --install-extension zxh404.vscode-proto3 --force
code --install-extension tabnine.tabnine-vscode --force
code --install-extension wakatime.vscode-wakatime --force
