env:
  TERM: alacritty

window:
  decorations: full

  padding:
    x: 10
    y: 10

# Colors (Solarized Light)
colors:
  # Default colors
  primary:
    background: '#fdf6e3' # base3
    foreground: '#657b83' # base00

  # Cursor colors
  cursor:
    text:   '#fdf6e3' # base3
    cursor: '#657b83' # base00

  # Normal colors
  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2

  # Bright colors
  bright:
    black:   '#002b36' # base03
    red:     '#cb4b16' # orange
    green:   '#586e75' # base01
    yellow:  '#657b83' # base00
    blue:    '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan:    '#93a1a1' # base1
    white:   '#fdf6e3' # base3


font:
  # Normal font face - Also used to draw glyphs on tmux & VIM
  normal:
    # Font name
    family: Fira Mono
    # Font face
    style: Retina

  # Bold font face
  bold:
    family: Fira Mono
    style: Bold

  # Italic font face
  italic:
    family: Fira Mono
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Fira Mono
    style: Italic

  # Font size
  size: 12.0

# Setup some amazing custom key bindings here - Best thing is you can setup key bindings
# using Mac's 'command' to control your tmux.
# A great reference: https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/#make-alacritty-feel-like-iterm2
key_bindings:
  # Use command + [ - to go to previous tmux window
  - { key: LBracket, mods: Command, chars: "\x5c\x70" }
  # Use command + ] - to go to previous tmux window
  - { key: RBracket, mods: Command, chars: "\x5c\x6e" }
  # ctrl-^ doesn't work in some terminals like alacritty
  - { key: Key6, mods: Control, chars: "\x1e" }