env:
  TERM: alacritty

window:

  padding:
    x: 12
    y: 12
  
  dynamic_padding: true

# Colors (Solarized Light)
colors:
  # Default colors
  primary:
    background: '#fdf6e3' # base3
    foreground: '#657b83' # base00

  # Cursor colors
  cursor:
    text:   '#fdf6e3' # base3
    cursor: '#657b83' # base00

  # Normal colors
  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2

  # Bright colors
  bright:
    black:   '#002b36' # base03
    red:     '#cb4b16' # orange
    green:   '#586e75' # base01
    yellow:  '#657b83' # base00
    blue:    '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan:    '#93a1a1' # base1
    white:   '#fdf6e3' # base3


font:
  # Normal font face - Also used to draw glyphs on tmux & VIM
  normal:
    # Font name
    family: JetBrains Mono
    # Font face
    style: Retina

  # Bold font face
  bold:
    family: JetBrains Mono
    style: Bold

  # Italic font face
  italic:
    family: JetBrains Mono
    style: Italic

  # Bold italic font face
  bold_italic:
    family: JetBrains Mono
    style: Italic

  # Font size
  size: 12.0

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }


selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to both the primary and
  # the selection clipboard. Otherwise, it will only be copied to the selection
  # clipboard.
  save_to_clipboard: true

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block
  unfocused_hollow: false

shell:
  program: /usr/bin/zsh
  args:
    - --login

# Setup some amazing custom key bindings here - Best thing is you can setup key bindings
# using Mac's 'command' to control your tmux.
# A great reference: https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/#make-alacritty-feel-like-iterm2
key_bindings:
  # Use command + [ - to go to previous tmux window
  #- { key: LBracket, mods: Command, chars: "\x5c\x70" }
  # Use command + ] - to go to previous tmux window
  #- { key: RBracket, mods: Command, chars: "\x5c\x6e" }
  # ctrl-^ doesn't work in some terminals like alacritty
  # - { key: Key6, mods: Control, chars: "\x1e" }
  - { key: V,        mods: Control|Shift,           action: Paste            }
  - { key: C,        mods: Control|Shift,           action: Copy             }
  - { key: F,        mods: Control|Shift,           action: SearchForward    }
  - { key: B,        mods: Control|Shift,           action: SearchBackward   }
  - { key: C,        mods: Control|Shift, mode: Vi, action: ClearSelection   }
  - { key: Insert,   mods: Shift,                   action: PasteSelection   }
  - { key: Key0,     mods: Control,                 action: ResetFontSize    }
  - { key: Equals,   mods: Control,                 action: IncreaseFontSize }
  - { key: Add,      mods: Control,                 action: IncreaseFontSize }
  - { key: Subtract, mods: Control,                 action: DecreaseFontSize }
  - { key: Minus,    mods: Control,                 action: DecreaseFontSize }

