---

- name: Links emacs daemon config | file
  become: yes
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/emacs/emacsd.service"
    dest: "/etc/systemd/system/emacsd.service"
    state: link
    force: yes

- name: Enable emacsd service | service
  service:
    name: emacsd
    enabled: yes
    state: started

- name: Install doom emacs | shell
  shell: |
    git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
    ~/.emacs.d/bin/doom install

- name: Removes doom config directory | file
  file:
    path: "{{ lookup('env', 'HOME') }}/.doom.d"
    state: absent

- name: Copy over doom configs | file
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/emacs/files/doom.d"
    dest: "{{ lookup('env', 'HOME') }}/.doom.d"
    state: link
    force: yes

- name: Install wakatime | pip
  pip:
    name: wakatime
  become: yes
