---
- name: Install emacs | package
  package:
    name: "emacs"
    state: "present"

- name: Install spacemacs | shell
  shell: |
    git clone --depth 1 https://github.com/syl20bnr/spacemacs ~/.emacs.d

- name: Copy over config file | file
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/emacs/files/spacemacs"
    dest: "{{ lookup('env', 'HOME') }}/.spacemacs"
    state: link
    force: yes
...
